[versions]
agp = "9.0.0"

junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"

appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.2"
constraintlayout = "2.2.1"

mpchart = "3.1.0"


# Firebase & Google (SAFE + STABLE)
firebaseBom = "34.0.0"
googleAuth = "21.0.0"


[libraries]
# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

# AndroidX
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

# Firebase (BOM based)
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }

# Google Sign-In
google-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "googleAuth" }

mpandroidchart = { group = "com.github.PhilJay", name = "MPAndroidChart", version.ref = "mpchart" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
